#syntax=docker/dockerfile:1.4
FROM eeems/remarkable-toolchain:base

COPY --from=eeems/remarkable-toolchain:5.7.119-rm1 /opt/codex/rm1 /opt/codex/rm1
COPY --from=eeems/remarkable-toolchain:5.7.119-rm2 /opt/codex/rm2 /opt/codex/rm2
